# Generated by Django 2.0.5 on 2018-05-27 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0002_auto_20180527_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xuehao', models.IntegerField(max_length=10, unique=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.TeacherInfo')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.ThesisInfo')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.Type')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
